import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import * as cheerio from 'cheerio'

const SOURCE_URL = process.argv[2] ?? 'https://rating.taiko.wiki/measure'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const OUTPUT_PATH = path.resolve(__dirname, '../src/lib/analyzerData.ts')

function formatConstant (cc) {
  return cc.toString()
}

function parseEntries (html) {
  const $ = cheerio.load(html)
  const rows = $('table tbody tr').toArray()

  if (rows.length === 0) {
    throw new Error('Measure table rows were not found in the fetched HTML.')
  }

  const rawEntries = rows.map((row) => {
    const cells = $(row).find('td')
    const ccText = $(cells[0]).text().trim()
    const href = $(cells[2]).find('a').attr('href') ?? ''
    const match = href.match(/\/song\/(\d+)\?diff=(oni|ura)\b/)

    if (match == null) {
      throw new Error(`Unexpected song link format: ${href}`)
    }

    const cc = Number(ccText)
    if (Number.isNaN(cc)) {
      throw new Error(`Unexpected CC value: ${ccText}`)
    }

    return {
      cc,
      ccKey: ccText,
      songno: Number(match[1]),
      diff: match[2]
    }
  })

  return rawEntries.map((entry) => ({
    constant: formatConstant(entry.cc),
    songno: entry.songno,
    diff: entry.diff
  }))
}

function renderFile (entries) {
  const body = entries
    .map(({ constant, songno, diff }) => `  { constant: ${constant}, songno: ${songno}, diff: ${diff} }`)
    .join(',\n')

  return `const ura = 'oni_ura'
const oni = 'oni'

// This file is generated by \`npm run generate:analyzer-data\`.
// Source: ${SOURCE_URL}
export const data = [
${body}
]
`
}

const response = await fetch(SOURCE_URL)
if (!response.ok) {
  throw new Error(`Failed to fetch ${SOURCE_URL}: ${response.status} ${response.statusText}`)
}

const html = await response.text()
const entries = parseEntries(html)
await writeFile(OUTPUT_PATH, renderFile(entries), 'utf8')

console.log(`Wrote ${entries.length} entries to ${OUTPUT_PATH}`)
